_wandb:
    value:
        cli_version: 0.21.1
        e:
            flma8gqc9czq6ea48qv3pyfzm78jvzag:
                args:
                    - --dataset
                    - 20newsgroups
                    - --seed
                    - "42"
                codePath: experiments/run_benchmark.py
                codePathLocal: experiments/run_benchmark.py
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: 0078dfc19c638993433b4ef624cea4bd42b33610
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/experiments/run_benchmark.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T03:58:11.835332Z"
                writerId: flma8gqc9czq6ea48qv3pyfzm78jvzag
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
dataset:
    value: 20newsgroups
git_hash:
    value: 0078dfc19c638993433b4ef624cea4bd42b33610
k:
    value: 15
run_timestamp_utc:
    value: 2025-08-14T03:58:11.398019
seed:
    value: 42
