_wandb:
    value:
        cli_version: 0.21.1
        e:
            lccabsq73uqzbg2a187isqrte579b0xy:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - --dataset
                    - agnews
                    - --method
                    - bertopic
                    - --seed
                    - "48"
                codePath: experiments/run_benchmark.py
                codePathLocal: experiments/run_benchmark.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "106507218944"
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: 25e066553e7816e9d3577c5422516cff3a538f1f
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                memory:
                    total: "17179869184"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/scripts/../experiments/run_benchmark.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T04:30:14.392281Z"
                writerId: lccabsq73uqzbg2a187isqrte579b0xy
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": darwin-arm64
dataset:
    value: agnews
git_hash:
    value: 25e066553e7816e9d3577c5422516cff3a538f1f
k:
    value: 15
method:
    value: bertopic
run_timestamp_utc:
    value: 2025-08-14T04:30:13.997726
seed:
    value: 48
