_wandb:
    value:
        cli_version: 0.21.1
        e:
            hnvn43mj9qonqcryc0ijbs9izekvbccm:
                args:
                    - --method
                    - hdbscan
                    - --dataset
                    - 20newsgroups
                    - --seed
                    - "42"
                codePath: experiments/run_benchmark.py
                codePathLocal: experiments/run_benchmark.py
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: f79709434658e41a76b218753d42801589101987
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/experiments/run_benchmark.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T04:02:25.912353Z"
                writerId: hnvn43mj9qonqcryc0ijbs9izekvbccm
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 75
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": darwin-arm64
dataset:
    value: 20newsgroups
git_hash:
    value: f79709434658e41a76b218753d42801589101987
k:
    value: 15
method:
    value: hdbscan
run_timestamp_utc:
    value: 2025-08-14T04:02:25.529307
seed:
    value: 42
