_wandb:
    value:
        cli_version: 0.21.1
        e:
            f6xhgd0ryjjvrxbsel7pm4pam9e0yetd:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - --method
                    - jormungandr
                    - --dataset
                    - agnews
                    - --seed
                    - "101"
                codePath: experiments/run_benchmark.py
                codePathLocal: experiments/run_benchmark.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "108450770944"
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: 4ccd421737412d7e7c9b860031920a067bd8c37f
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                memory:
                    total: "17179869184"
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/experiments/run_benchmark.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T09:31:43.206885Z"
                writerId: f6xhgd0ryjjvrxbsel7pm4pam9e0yetd
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": darwin-arm64
dataset:
    value: agnews
git_hash:
    value: 4ccd421737412d7e7c9b860031920a067bd8c37f
k:
    value: 15
method:
    value: jormungandr
run_timestamp_utc:
    value: 2025-08-14T09:31:42.825354
seed:
    value: 101
umap_dims:
    value: 5
