_wandb:
    value:
        cli_version: 0.21.1
        e:
            nhpkoke2wtcbhw0nbs10va52hrbhweg7:
                codePath: scripts/verify_install.py
                codePathLocal: scripts/verify_install.py
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: 8e2a92d577e15ea88e9f3c0856e85cea2c796035
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/scripts/verify_install.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T03:47:45.935470Z"
                writerId: nhpkoke2wtcbhw0nbs10va52hrbhweg7
        m: []
        python_version: 3.10.18
        t:
            "3":
                - 2
            "4": 3.10.18
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
data_source:
    value: random_uniform
k:
    value: 10
n_dims:
    value: 16
n_points:
    value: 100
