_wandb:
    value:
        cli_version: 0.21.1
        e:
            ieli3182djfxj9a1c71reyf5au2trlng:
                args:
                    - --dataset
                    - agnews
                    - --method
                    - jormungandr
                    - --seed
                    - "46"
                codePath: experiments/run_benchmark.py
                codePathLocal: experiments/run_benchmark.py
                email: mohan.rangan.research@gmail.com
                executable: /opt/homebrew/Caskroom/miniforge/base/envs/principia/bin/python
                git:
                    commit: 25e066553e7816e9d3577c5422516cff3a538f1f
                    remote: https://github.com/NOSFERA-Institute-of-Thought-Systems/Jormungandr-Semantica.git
                host: Mohanas-Mac-mini.local
                os: macOS-15.6-arm64-arm-64bit
                program: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica/scripts/../experiments/run_benchmark.py
                python: CPython 3.10.18
                root: /Users/mohanarangandesigan/Developer/GitHub/Jormungandr-Semantica
                startedAt: "2025-08-14T04:27:46.257941Z"
                writerId: ieli3182djfxj9a1c71reyf5au2trlng
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 75
            "3":
                - 2
                - 16
            "4": 3.10.18
            "5": 0.21.1
            "6": 4.55.2
            "12": 0.21.1
            "13": darwin-arm64
dataset:
    value: agnews
git_hash:
    value: 25e066553e7816e9d3577c5422516cff3a538f1f
k:
    value: 15
method:
    value: jormungandr
run_timestamp_utc:
    value: 2025-08-14T04:27:45.880999
seed:
    value: 46
