# File: .github/workflows/ci.yml

name: Build and Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-file: environment.yml
          activate-environment: aglt # Use the new environment name

      - name: Build and install project with dev dependencies
        # THIS IS THE FIX: The shell command `bash -l {0}` makes conda available.
        # We also install with the [dev] extras to get pytest.
        shell: bash -l {0}
        run: |
          pip install -e ".[dev]" --no-cache-dir

      - name: Run the full test suite
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        # Use the same login shell for consistency
        shell: bash -l {0}
        run: |
          pytest
